version: 0.0
Resources:
- myK8sResources:
Type: AWS::ECS::Service # placeholder; CodeDeploy for EKS uses a specific setup
Properties: {}
hooks:
BeforeInstall:
- location: scripts/before_install.sh
timeout: 300
AfterInstall:
- location: scripts/after_install.sh
timeout: 300
ApplicationStart:
- location: scripts/start_app.sh
timeout: 300
